### ISSUE TITLE
Feedback Request: MiniProject

### ISSUE THREAD

**Issue by sasudi90** [TechGrounds-Cloud8/cloud8-sasudi90#47]
**Feedback Request [MiniProject]**
Permalink to file: [LINK](https://github.com/TechGrounds-Cloud8/cloud8-sasudi90/blob/da81da8215e8d97743a7fae3f68f706ebc75db90/07_Python/MiniProject/RPS.py)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Really nicely done by splitting every logical section up in different functions!

Your scoring system is very smart, using the indexes... I've never seen that before :D nice one!

It's interesting that the validate functions works, because the 'moves' list isn't passed to it... So I would kinda expect a similar error as you had with scoreboard, but hey if it works it works xD

tiny bug:
- "You Draw" xD

suggestions:
- When the game is over, it just finishes after the last round. Maybe the script can congratulate me (if I won) and roast me if I lose?
- maybe you could make it scalable, so after filling out my name, it asks how many rounds I want to play?
